version: "3.7"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-docker
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-docker
    restart: always
    links:
      - "mysql:db"
    ports:
      - 8080:80
    volumes:
      - /sessions
  web:
    build: .
    container_name: adonis-docker
    ports:
      - "3333:3333"
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - mysql
volumes:
  database:
    driver: "local"
